/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "probe1_aliases.h"
#include "probe1.h"
#include "ADCInt1.h"
#include "Clock_1.h"
#include "ADCDMA1_dma.h"
#include "probe2_aliases.h"
#include "probe2.h"
#include "USBFS.h"
#include "USBFS_audio.h"
#include "USBFS_cdc.h"
#include "USBFS_hid.h"
#include "USBFS_midi.h"
#include "USBFS_pvt.h"
#include "USBFS_cydmac.h"
#include "USBFS_msc.h"
#include "ADC_SAR_1.h"
#include "ADC_DelSig.h"
#include "potSelect.h"
#include "potChannel1_aliases.h"
#include "potChannel1.h"
#include "potChannel2_aliases.h"
#include "potChannel2.h"
#include "ADC_SAR_2.h"
#include "ADCDMA2_dma.h"
#include "ADCInt2.h"
#include "USBFS_Dm_aliases.h"
#include "USBFS_Dm.h"
#include "USBFS_Dp_aliases.h"
#include "USBFS_Dp.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_1_Bypass_aliases.h"
#include "ADC_SAR_1_Bypass.h"
#include "ADC_DelSig_AMux.h"
#include "ADC_DelSig_Ext_CP_Clk.h"
#include "ADC_DelSig_IRQ.h"
#include "ADC_DelSig_theACLK.h"
#include "ADC_SAR_2_IRQ.h"
#include "ADC_SAR_2_theACLK.h"
#include "ADC_SAR_2_Bypass_aliases.h"
#include "ADC_SAR_2_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

